"""Transform registry with TemplateFlow integration.

This module provides registry and metadata for spatial transformations
between coordinate spaces.
"""

from __future__ import annotations

from dataclasses import dataclass

from lacuna.assets.base import AssetMetadata, AssetRegistry


@dataclass(frozen=True)
class TransformMetadata(AssetMetadata):
    """Metadata for a spatial transformation.

    Attributes
    ----------
    name : str
        Transform identifier (e.g., "MNI152NLin6Asym_to_MNI152NLin2009cAsym")
    description : str
        Human-readable description
    from_space : str
        Source coordinate space
    to_space : str
        Target coordinate space
    transform_type : str
        Type of transform ("nonlinear", "affine", "composite")
    source : str
        Origin of the transform data (e.g. "templateflow", redistributed via OSF)
    url : str
        Download URL for the transform file (fetched and cached on first use)
    sha256 : str
        Expected SHA-256 of the transform file (verified on download)
    """

    from_space: str = ""
    to_space: str = ""
    transform_type: str = "nonlinear"
    source: str = "templateflow"
    url: str = ""
    sha256: str = ""

    def validate(self) -> None:
        """Validate transform metadata.

        Raises
        ------
        ValueError
            If metadata is invalid
        """
        from lacuna.core.spaces import SUPPORTED_SPACES

        # Check spaces
        for space in [self.from_space, self.to_space]:
            if space and space not in SUPPORTED_SPACES:
                raise ValueError(f"Unsupported space: {space}. " f"Supported: {SUPPORTED_SPACES}")


# Create registry and populate with known transforms
TRANSFORM_REGISTRY = AssetRegistry[TransformMetadata]("transform")

# Nonlinear warps between MNI152NLin6Asym and MNI152NLin2009cAsym.
# Generated by TemplateFlow (templateflow.org) and redistributed via OSF
# (https://osf.io/yz9mb/) with attribution; downloaded and cached on first use.
# URL<->file mapping verified by content hash, not by filename/label.
_KNOWN_TRANSFORMS = [
    TransformMetadata(
        name="MNI152NLin6Asym_to_MNI152NLin2009cAsym",
        description="Nonlinear transform from MNI152 6th gen to 2009c",
        from_space="MNI152NLin6Asym",
        to_space="MNI152NLin2009cAsym",
        transform_type="nonlinear",
        # tpl-MNI152NLin2009cAsym_from-MNI152NLin6Asym_mode-image_xfm.h5
        url="https://osf.io/hzjqr/download",
        sha256="2e3869a07b96aec406e0419ca2e434afc54882d37cc212b933b139d1b63a4dfe",
    ),
    TransformMetadata(
        name="MNI152NLin2009cAsym_to_MNI152NLin6Asym",
        description="Nonlinear transform from MNI152 2009c to 6th gen",
        from_space="MNI152NLin2009cAsym",
        to_space="MNI152NLin6Asym",
        transform_type="nonlinear",
        # tpl-MNI152NLin6Asym_from-MNI152NLin2009cAsym_mode-image_xfm.h5
        url="https://osf.io/9gsta/download",
        sha256="2a19853bc99ebd1d711d230ea4a4dc4db3b9a60f8b50b9181f93b44036dfbd0f",
    ),
]

for transform in _KNOWN_TRANSFORMS:
    TRANSFORM_REGISTRY.register(transform)


def list_transforms(
    from_space: str | None = None,
    to_space: str | None = None,
) -> list[TransformMetadata]:
    """List available transforms from TemplateFlow.

    Parameters
    ----------
    from_space : str, optional
        Filter by source coordinate space
    to_space : str, optional
        Filter by target coordinate space

    Returns
    -------
    list[TransformMetadata]
        Matching transforms

    Examples
    --------
    >>> from lacuna.assets.transforms import list_transforms
    >>>
    >>> # List all available transforms
    >>> transforms = list_transforms()
    >>>
    >>> # Find transforms from NLin6 to NLin2009c
    >>> transforms = list_transforms(
    ...     from_space="MNI152NLin6Asym",
    ...     to_space="MNI152NLin2009cAsym"
    ... )
    """
    # Use registry filtering
    # Note: AssetRegistry.list() doesn't support from_space/to_space directly,
    # so we need to filter manually
    all_transforms = TRANSFORM_REGISTRY.list()

    if from_space is not None:
        all_transforms = [t for t in all_transforms if t.from_space == from_space]

    if to_space is not None:
        all_transforms = [t for t in all_transforms if t.to_space == to_space]

    return all_transforms


__all__ = [
    "TransformMetadata",
    "TRANSFORM_REGISTRY",
    "list_transforms",
]
